---
name: Set up Playwright

description: Sets up the workflow context for Playwright tests.

inputs:
  working-directory:
    description: The working directory where package.json is
    default: '.'

outputs:
  cache-hit:
    description: Whether the dependency cache was a hit
    value: ${{ steps.cache-deps.outputs.cache-hit }}
  cache-path:
    description: The path to the cached dependencies
    value: ${{ steps.playwright-info.outputs.path }}
  playwright-version:
    description: Which version of Playwright is installed
    value: ${{ steps.playwright-info.outputs.version }}

runs:
  using: composite
  steps:
    - name: Get OS information
      id: os-info
      shell: bash
      run: |
        case "$RUNNER_OS" in
          Linux)
            if [[ -f '/etc/lsb-release' ]] && [[ "$(cat '/etc/lsb-release' | grep 'DISTRIB_ID' | cut -d= -f2)" == 'Ubuntu' ]]; then
              echo "os=ubuntu-$(cat '/etc/lsb-release' | grep 'DISTRIB_RELEASE' | cut -d= -f2)" >> $GITHUB_OUTPUT
            else
              echo "os=Linux" >> $GITHUB_OUTPUT
            fi
            ;;
          *)
            echo "os=$RUNNER_OS" >> $GITHUB_OUTPUT
            ;;
        esac
    - name: Get Playwright information
      id: playwright-info
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "version=$(npx playwright --version | awk '{print $2}')" >> $GITHUB_OUTPUT
        # https://playwright.dev/docs/browsers#managing-browser-binaries
        case "$RUNNER_OS" in
          Linux)
            echo 'path=~/.cache/ms-playwright' >> $GITHUB_OUTPUT
            ;;
          macOS)
            echo 'path=~/Library/Caches/ms-playwright' >> $GITHUB_OUTPUT
            ;;
          Windows)
            echo "path=C:\\Users\\$(whoami)\AppData\Local\ms-playwright" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Unknown OS: $OS"
            exit 1
            ;;
        esac
    - name: Cache Playwright dependencies
      id: cache-deps
      uses: actions/cache@v6
      with:
        key: ${{ steps.os-info.outputs.os }}-playwright-deps-${{ steps.playwright-info.outputs.version }}
        path: ${{ steps.playwright-info.outputs.path }}
    - name: Install Playwright dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npx playwright install --with-deps
