---
name: Test nodejs action

on:
  push:
    branches: [ 'main', 'nodejs', 'test/nodejs' ]
  pull_request:
    branches: [ 'main', 'nodejs', 'test/nodejs' ]
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]
        package-manager: [ 'npm', 'pnpm', 'yarn' ]
        example: [ 'example' ]
        node-version: [ 'lts/*' ]
        include:
          - os: 'ubuntu-latest'
            example: 'example-pkg'
            package-manager: 'npm'
            node-version: ''
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: test/nodejs
    - uses: textbook/take-action@nodejs
      id: nodejs-action
      with:
        checkout: false
        node-version: ${{ matrix.node-version }}
        working-directory: ${{ matrix.package-manager }}-${{ matrix.example }}
    - run: echo '${{ toJSON(steps.nodejs-action.outputs) }}'
    - run: ${{ matrix.package-manager }} test
      working-directory: ${{ matrix.package-manager }}-${{ matrix.example }}
  